version: "2.3"
services:
    wros_noetic_ws:
        build:
            context: "docker"
            dockerfile: "Dockerfile"
        container_name: wros_noetic_container
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            # to transport X11 application window
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROS_HOSTNAME=localhost
        volumes:
            # for USB devices
            - /dev:/dev
            # to tansport X11 application (require xhost local:)
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # ros catkin dir
            - ./catkin_ws/noetic/src/wros_tutorials:/catkin_ws/src/wros_tutorials
            - ./catkin_ws/noetic/src/wros_tutorials/modules/wrs:/catkin_ws/src/wros_tutorials/modules/wrs
        privileged: true
        tty: true
        network_mode: host
        command: bash -c "source /opt/ros/noetic/setup.bash && catkin build -DPYTHON_EXECUTABLE=/usr/bin/python3 && bash"
