object_mesh_path: '/catkin_ws/src/wros_tutorials/meshes/milkcarton.stl'
obstcl_mesh_path: '/catkin_ws/src/wros_tutorials/meshes/table.stl'
vis_failures: True
save_results: False
gripper_name: 'robotiq140'
antipodal_grasp:
    angle_between_contact_normals: 90
    openning_direction: 'loc_y' 
    max_samples: 4
    min_dist_between_sampled_contact_points: .016
    contact_offset: .016 